# Generated by Django 2.1.3 on 2018-11-19 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('seccion', models.CharField(max_length=60)),
                ('incripcion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('creditos', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pemsum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, null=True)),
                ('descripcion', models.CharField(max_length=60, null=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Grado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Materia')),
            ],
        ),
        migrations.AddField(
            model_name='grado',
            name='materia',
            field=models.ManyToManyField(through='aplicacion.Pemsum', to='aplicacion.Materia'),
        ),
    ]
